# -*- coding: utf-8 -*-
"""Copy of Lina_202120685.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tDd4DJCuUKQn1TH1w4jcLYbSommzFPjS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('netflix_titles.csv')

# Confirm loading
print("Data Loaded Successfully!")
df.head()

# Task 2: Data Cleaning
df.drop_duplicates(inplace=True)
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')
df.dropna(subset=['date_added', 'rating', 'duration'], inplace=True)

# Prepare numeric duration for movies
movies_only = df[df['type'] == 'Movie'].copy()
movies_only['duration_min'] = movies_only['duration'].str.replace(' min', '').fillna('0').astype(int)

print("Data cleaning completed. Ready for visualization.")

# 1. Bar Chart: Content Type
plt.figure(figsize=(8, 5))
df['type'].value_counts().plot(kind='bar', color=['#b20710', '#221f1f'])
plt.title('1. Content Type Comparison', fontsize=14, fontweight='bold')
plt.xlabel('Type')
plt.ylabel('Count')
plt.tight_layout()
plt.show()

# 2. Histogram: Release Years
plt.figure(figsize=(8, 5))
plt.hist(df['release_year'], bins=30, color='#b20710', edgecolor='white')
plt.title('2. Distribution of Release Years', fontsize=14, fontweight='bold')
plt.xlabel('Year')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

# 3. Line Chart: Trend Over Time
plt.figure(figsize=(8, 5))
yearly_counts = df['release_year'].value_counts().sort_index()
plt.plot(yearly_counts.index, yearly_counts.values, marker='o', color='red', linewidth=2)
plt.title('3. Trend of Content Added Over Years', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# 4. Scatter Plot: Year vs Duration
plt.figure(figsize=(8, 5))
sample_data = movies_only.sample(100) # Use sample to avoid crowding
plt.scatter(sample_data['release_year'], sample_data['duration_min'], color='darkblue', alpha=0.6)
plt.title('4. Release Year vs Movie Duration', fontsize=14, fontweight='bold')
plt.xlabel('Release Year')
plt.ylabel('Duration (min)')
plt.tight_layout()
plt.show()

# 5. Pie Chart: Ratings
plt.figure(figsize=(7, 7))
df['rating'].value_counts().head(5).plot(kind='pie', autopct='%1.1f%%', colors=['#b20710', '#e50914', '#f5f5f1', '#221f1f', '#8c8c8c'])
plt.title('5. Top 5 Content Ratings', fontsize=14, fontweight='bold')
plt.ylabel('') # Hide the 'rating' label
plt.tight_layout()
plt.show()

# 6. Subplot: Combined View
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
df['type'].value_counts().plot(kind='bar', ax=ax1, color='red')
ax1.set_title('Content Types')
df['release_year'].hist(ax=ax2, bins=20, color='black', alpha=0.7)
ax2.set_title('Release Year Dist.')
plt.suptitle('6. Combined Dashboard Overview', fontsize=16, fontweight='bold')
plt.tight_layout()
plt.show()

# 7. Distribution Plot (Seaborn)
plt.figure(figsize=(8, 5))
sns.histplot(movies_only['duration_min'], kde=True, color='purple')
plt.title('7. Distribution of Movie Durations', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# 8. Categorical Plot (Seaborn)
plt.figure(figsize=(10, 5))
sns.countplot(data=df, x='rating', order=df['rating'].value_counts().index[:8], palette='viridis')
plt.title('8. Top Content Ratings (Categorical)', fontsize=14, fontweight='bold')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 9. Relational Plot (Seaborn)
plt.figure(figsize=(8, 5))
sns.scatterplot(data=movies_only.sample(200), x='release_year', y='duration_min', hue='rating')
plt.title('9. Year vs Duration (Colored by Rating)', fontsize=14, fontweight='bold')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

# 10. FacetGrid (Special Seaborn Plot)
top_ratings = ['TV-MA', 'TV-14', 'TV-PG']
g = sns.FacetGrid(df[df['rating'].isin(top_ratings)], col="rating", height=4)
g.map(plt.hist, "release_year", color="coral", bins=20)
g.fig.suptitle('10. Release Year Trends by Rating', y=1.05, fontsize=14, fontweight='bold')
plt.show()

# Task 5: Written Analytical Summary
summary = """
Introduction:
In this project, I explored the Netflix dataset. The main goal was to clean the data
and find patterns. After fixing missing values, I created several charts.

Key Patterns:
1. Based on the Bar Chart, Netflix has more Movies than TV Shows.
2. The Line Chart shows a massive increase in content after 2015.
3. The Distribution Plot shows most movies are around 90-120 minutes.

Recommendations:
- Netflix should produce more TV Shows to balance the content.
- Target mature audiences (TV-MA) as it is the most common rating.
"""
print(summary)

import plotly.express as px

# 1. Interactive Bar Chart: Content Types
# تجهيز البيانات وتسمية الأعمدة
type_counts = df['type'].value_counts().reset_index()
type_counts.columns = ['Content Type', 'Count']

fig1 = px.bar(type_counts,
             x='Content Type',
             y='Count',
             title='1. Interactive Content Type Comparison',
             color='Content Type',
             color_discrete_map={'Movie': '#b20710', 'TV Show': '#221f1f'}) # ألوان نتفليكس
fig1.show()

# 2. Interactive Histogram: Release Years
fig2 = px.histogram(df, x="release_year",
                   title='2. Interactive Distribution of Release Years',
                   nbins=30,
                   color_discrete_sequence=['#b20710'])
fig2.show()

# 3. Interactive Scatter Plot: Year vs Duration

fig3 = px.scatter(movies_only.sample(200),
                 x="release_year",
                 y="duration_min",
                 color="rating",
                 hover_data=['title'],
                 title="3. Interactive Year vs Duration (Hover for Details)")
fig3.show()

import pandas as pd
from dash import Dash, dcc, html, Input, Output
import plotly.express as px

df = pd.read_csv('netflix_titles.csv')

app = Dash(__name__)

app.layout = html.Div([
    html.H1("Netflix Content Analysis", style={'textAlign': 'center', 'color': '#b20710'}),

    html.Div([
        html.Label("Filter by Type:"),
        dcc.Dropdown(
            id='type-selection',
            options=[{'label': i, 'value': i} for i in df['type'].unique()],
            value='Movie',
            style={'width': '50%'}
        ),
    ], style={'padding': '20px'}),

    dcc.Graph(id='main-visualization')
])

@app.callback(
    Output('main-visualization', 'figure'),
    Input('type-selection', 'value')
)
def update_content_graph(selected_type):
    filtered_df = df[df['type'] == selected_type]
    fig = px.histogram(filtered_df, x="release_year",
                       title=f"Distribution of {selected_type}s by Year",
                       color_discrete_sequence=['#b20710'])
    return fig
()app.run
